/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicInfo: typeof import('./src/components/BasicInfo.vue')['default']
    CommentSection: typeof import('./src/components/CommentSection.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRate: typeof import('element-plus/es')['ElRate']
    PopRecom: typeof import('./src/components/PopRecom.vue')['default']
    PopReviews: typeof import('./src/components/PopReviews.vue')['default']
    RecentPopularComp: typeof import('./src/components/RecentPopularComp.vue')['default']
    RelatedImages: typeof import('./src/components/RelatedImages.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubjectRight: typeof import('./src/components/SubjectRight.vue')['default']
  }
}
